#!/bin/bash
set -euo pipefail

PACKAGES=(
  subversion g++ zlib1g-dev build-essential git python python3 rsync man-db
  libncurses5-dev gawk gettext unzip file libssl-dev wget zip
)

apt-get install -y "${PACKAGES[@]}"
