#!/bin/bash
set -euo pipefail

PACKAGES=(
  build-essential
  bzr
  ccache
  curl
  ecj
  fastjar
  file
  g++
  gawk
  gettext
  git
  java-propose-classpath
  jq
  libelf-dev
  libncurses5-dev
  libncursesw5-dev
  libssl-dev
  libxml-parser-perl
  man-db
  python
  python3
  python3-distutils
  python3-setuptools
  rsync
  signify-openbsd
  subversion
  swig
  time
  unzip
  wget
  xsltproc
  xz-utils
  zip
  zlib1g-dev
)

apt-get install -y "${PACKAGES[@]}"
